on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: moonrepo/setup-rust@v1
        with:
          cache: false

      - id: build
        uses: moonrepo/build-wasm-plugin@v0

      - name: Semver
        id: semver
        uses: oknozor/cocogitto-action@v3
        with:
          release: true
          git-user: "Bot"
          git-user-email: "proto-plugin-poetry@localhost"

      - name: Changelog generate
        id: changelog
        run: |
          cog changelog --at ${{ steps.semver.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md
        shell: bash

      - name: Upload github release
        uses: softprops/action-gh-release@v2
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.semver.outputs.version }}
          make_latest: true
          files: |
            builds/poetry_plugin.wasm
            builds/poetry_plugin.wasm.sha256
            GITHUB_CHANGELOG.md
